### ISSUE TITLE
不显示内容

### ISSUE THREAD

**Issue by xiaotiandada** [xiangming25/react-intl-umi#1]
好久没打开项目今天突然不正常工作了，试了半天没办法看看作者是否遇到相关的情况。

试试过 `v0.1.0 v0.9.0 v0.8.0` 三个版本

vscode 版本
```
Version: 1.64.0 (Universal)
```
<img width="293" alt="image" src="https://user-images.githubusercontent.com/24250627/152937561-66213b67-816a-4b88-9bca-d1a50a74f2c8.png">

结果
<img width="705" alt="image" src="https://user-images.githubusercontent.com/24250627/152937468-76856457-a3fe-4940-a3d3-0c2f55bc1ce4.png">

**Comment by xiangming25** [comment]
国际化配置文件在引入时，是使用的相对路径引入的吗？

**Comment by xiangming25** [comment]
> 好久没打开项目今天突然不正常工作了，试了半天没办法看看作者是否遇到相关的情况。
> 
> 试试过 `v0.1.0 v0.9.0 v0.8.0` 三个版本
> 
> vscode 版本
> 
> ```
> Version: 1.64.0 (Universal)
> ```
> 
> <img alt="image" width="293" src="https://user-images.githubusercontent.com/24250627/152937561-66213b67-816a-4b88-9bca-d1a50a74f2c8.png">
> 
> 结果 <img alt="image" width="705" src="https://user-images.githubusercontent.com/24250627/152937468-76856457-a3fe-4940-a3d3-0c2f55bc1ce4.png">

**Comment by xiangming25** [comment]
> 好久没打开项目今天突然不正常工作了，试了半天没办法看看作者是否遇到相关的情况。
> 
> 试试过 `v0.1.0 v0.9.0 v0.8.0` 三个版本
> 
> vscode 版本
> 
> ```
> Version: 1.64.0 (Universal)
> ```
> 
> <img alt="image" width="293" src="https://user-images.githubusercontent.com/24250627/152937561-66213b67-816a-4b88-9bca-d1a50a74f2c8.png">
> 
> 结果 <img alt="image" width="705" src="https://user-images.githubusercontent.com/24250627/152937468-76856457-a3fe-4940-a3d3-0c2f55bc1ce4.png">

请问国际化配置文件的引入是使用相对路径引入的吗？

**Comment by xiaotiandada** [comment]
> > 好久没打开项目今天突然不正常工作了，试了半天没办法看看作者是否遇到相关的情况。
> > 试试过 `v0.1.0 v0.9.0 v0.8.0` 三个版本
> > vscode 版本
> > ```
> > Version: 1.64.0 (Universal)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="293" src="https://user-images.githubusercontent.com/24250627/152937561-66213b67-816a-4b88-9bca-d1a50a74f2c8.png">
> > 结果 <img alt="image" width="705" src="https://user-images.githubusercontent.com/24250627/152937468-76856457-a3fe-4940-a3d3-0c2f55bc1ce4.png">
> 
> 请问国际化配置文件的引入是使用相对路径引入的吗？

谢回复，刚启动项目和插件看了看 已正常工作。


当前版本
```
react-intl-umi: v0.1.0

vscode: Version: 1.65.1 (Universal)
```

**Comment by xiangming25** [comment]
OK, 使用中如果有遇见问题，欢迎反馈
